node {
    stage('Check Out') {
        cleanWs()
        git url: 'http://gitlab:80/gitlab/cbeldape/jenkins-session.git'
    }

    stage('Loading Custom Tools') {
        def node = tool name: 'NodeJS 8.9.4', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH = "${node}/bin:${env.PATH}"
        sh "npm i -g yarn"
        tool 'Chrome-stable'
    }
    
    stage('Fresh Dependency Installation') {
        sh "yarn"
    }
    
    stage('Code Linting') {
        sh "ng lint"
    }
    
    stage('Execute Angular tests') {
        sh "ng test --browsers ChromeHeadless --single-run"
    }
    
    stage('Build Application') {
        sh "ng build --prod --build-optimizer"
    }
    
    stage('Push Artifact to Nexus') {
        dir('java') {
            withMaven(globalMavenSettingsConfig: 'MavenSettings', jdk: 'OpenJDK 1.8', maven: 'Maven 3.3.9') {
                sh "mvn clean deploy -DskipTests"
            }
        }
    }
    
    stage('Execute Deployment Job') {
        build 'job'
    }
}